"""Phase 3 Expansion

Revision ID: 5f15014e525a
Revises: 0001
Create Date: 2026-09-20 05:53:22.184899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f15014e525a'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('damage_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reporter_id', sa.String(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_ground_reports_event_id'), 'ground_reports', ['event_id'], unique=False)
    op.create_index(op.f('ix_ground_reports_timestamp'), 'ground_reports', ['timestamp'], unique=False)

    op.add_column('classifications', sa.Column('damage_class', sa.String(length=64), nullable=True))
    op.add_column('classifications', sa.Column('severity_score', sa.Float(), nullable=True))
    op.add_column('classifications', sa.Column('t12_lat', sa.Float(), nullable=True))
    op.add_column('classifications', sa.Column('t12_lon', sa.Float(), nullable=True))
    op.add_column('classifications', sa.Column('t24_lat', sa.Float(), nullable=True))
    op.add_column('classifications', sa.Column('t24_lon', sa.Float(), nullable=True))
    
    op.create_index(op.f('ix_classifications_frame_id'), 'classifications', ['frame_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_frame_id'), table_name='classifications')
    op.drop_column('classifications', 't24_lon')
    op.drop_column('classifications', 't24_lat')
    op.drop_column('classifications', 't12_lon')
    op.drop_column('classifications', 't12_lat')
    op.drop_column('classifications', 'severity_score')
    op.drop_column('classifications', 'damage_class')
    
    op.drop_index(op.f('ix_ground_reports_timestamp'), table_name='ground_reports')
    op.drop_index(op.f('ix_ground_reports_event_id'), table_name='ground_reports')
    op.drop_table('ground_reports')
    # ### end Alembic commands ###
